[pytest]
# Adds the current directory to PYTHONPATH so 'app' can be imported
pythonpath = .

# Optional: Default flags (so you don't always have to type -v)
addopts = -v

# Where to look for tests
testpaths = tests